# Windows-compatible pre-commit configuration
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# Standard pre-commit hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: mixed-line-ending

# AI-powered code review hooks (PowerShell compatible)
-   repo: local
    hooks:
    # GitHub Copilot Code Review for individual files
    -   id: copilot-review
        name: GitHub Copilot Code Review
        entry: powershell.exe -Command "python scripts/copilot-review.py"
        language: system
        stages: [pre-commit]
        types: [file]
        files: \.(cs|js|ts|py|sql|razor|json|yml|yaml)$
        exclude: |
          (?x)^(
            bin/|
            obj/|
            node_modules/|
            \.git/|
            \.pre-commit-reviews/|
            Migrations/.*\.cs$|
            .*\.Designer\.cs$|
            .*\.g\.cs$|
            package-lock\.json$|
            yarn\.lock$
          )
        pass_filenames: true
        require_serial: true

    # Smart Review Filter - determines which files need detailed review
    -   id: smart-review-filter
        name: Smart Review Filter
        entry: powershell.exe -Command "python scripts/smart-filter.py"
        language: system
        stages: [pre-commit]
        files: \.(cs|razor|js|ts|sql|py)$
        pass_filenames: true
        verbose: true
