# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# Standard pre-commit hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: mixed-line-ending

# AI-powered code review hooks (Windows compatible - using Python directly)
-   repo: local
    hooks:
    # GitHub Copilot Code Review for individual files
    -   id: copilot-review
        name: GitHub Copilot Code Review
        entry: python
        args: [scripts/copilot-review.py]
        language: system
        stages: [pre-commit]
        types: [file]
        files: \.(cs|js|ts|py|sql|razor|json|yml|yaml)$
        exclude: |
          (?x)^(
            bin/|
            obj/|
            node_modules/|
            \.git/|
            \.pre-commit-reviews/|
            Migrations/.*\.cs$|
            .*\.Designer\.cs$|
            .*\.g\.cs$|
            package-lock\.json$|
            yarn\.lock$
          )
        pass_filenames: true
        require_serial: true

    # Smart Review Filter - determines which files need detailed review (info only)
    -   id: smart-review-filter
        name: Smart Review Filter (Complexity Analysis)
        entry: python
        args: [scripts/smart-filter.py]
        language: system
        stages: [manual]
        files: \.(cs|razor|js|ts|sql|py)$
        pass_filenames: true
        verbose: true

    # Batch Review for large changes (pre-push stage)
    -   id: batch-copilot-review
        name: Batch Copilot Review (Large Changes)
        entry: python
        args: [scripts/batch-review.py, --threshold=5, --priority=high]
        language: system
        stages: [pre-push]
        types: [file]
        files: \.(cs|js|ts|py|sql|razor)$
        pass_filenames: true
